package com.chirathi.voicebridge

import android.content.Context
import android.util.Log
import org.json.JSONObject
import org.tensorflow.lite.Interpreter
import java.io.FileInputStream
import java.nio.MappedByteBuffer
import java.nio.channels.FileChannel
import kotlin.math.ln
import kotlin.math.max

/**
 * GameMasterModel — v9.2
 *
 * ══ WHAT CHANGED vs PREVIOUS VERSION ══════════════════════════════════════
 *
 *  FIX 1 — Output mapping now loaded from output_mapping.json (assets/)
 *    Old code hardcoded OUTPUT_NAMES in alphabetical order and used positional
 *    fallback. The actual TFLite outputs were NOT in alphabetical order, causing
 *    17 out of 20 shape mismatches → all values read from wrong tensors.
 *
 *    New code reads output_mapping.json generated by the Python export script.
 *    The JSON contains the verified name→tflite_index mapping, confirmed by shape
 *    checks run at export time. Android never has to guess the order.
 *
 *  FIX 2 — StandardScaler normalization applied before inference
 *    The model was trained on StandardScaler-normalized features (mean/scale from
 *    training data). Feeding raw values (rt=3000, itl=1500) produced garbage.
 *    sub_routine showing [128.529] in logs confirmed unnormalized input.
 *
 *    New code reads scaler mean/scale from output_mapping.json and applies the
 *    same normalization to both current features and history buffer entries.
 *
 * ══ DEPLOYMENT ═══════════════════════════════════════════════════════════
 *    Both files must be in app/src/main/assets/:
 *      game_master.tflite
 *      output_mapping.json    ← new required file
 *
 * ══ STILL UNCHANGED ══════════════════════════════════════════════════════
 *    All inference wraps in try/catch → game never crashes.
 *    Input shapes: child_id=[1,1], history=[1,5,17], current=[1,17].
 *    Buffer allocation uses actual shapes from getOutputTensor().
 */
class GameMasterModel(private val context: Context) {

    companion object {
        private const val TAG               = "GameMasterModel"
        private const val MODEL_FILE        = "game_master_testing.tflite"
        private const val MAPPING_FILE      = "output_mapping.json"
        private const val NUM_FEATURES      = 17
        private const val HISTORY_STEPS     = 5
        private var _lastRawFeatures = FloatArray(NUM_FEATURES)

        // Fallback expected output sizes — used only if JSON fails to load.
        // Keep in sync with EXPECTED_OUTPUT_SIZES in Python.
        private val FALLBACK_EXPECTED_SIZES = mapOf(
            "connect_dots_trigger"   to 2,
            "distractor"             to 5,
            "emotion_level"          to 3,
            "friend_action"          to 10,
            "frustration_risk"       to 1,
            "future_engagement"      to 1,
            "hidden_step_index"      to 3,
            "interaction_mode"       to 3,
            "latency_buffer"         to 1,
            "minigame_difficulty"    to 3,
            "minigame_trigger"       to 2,
            "minigame_type"          to 4,
            "motivation"             to 3,
            "next_accuracy"          to 1,
            "optimal_difficulty"     to 4,
            "optimal_hint"           to 3,
            "rhythm_complexity"      to 1,
            "sub_routine"            to 3,
            "time_pressure"          to 3,
            "whats_missing_trigger"  to 2
        )

        // Alphabetical list used only as final positional fallback
        // if JSON fails AND name matching fails. Not the primary mapping path.
        private val FALLBACK_ALPHA_ORDER = listOf(
            "connect_dots_trigger", "distractor", "emotion_level", "friend_action",
            "frustration_risk", "future_engagement", "hidden_step_index", "interaction_mode",
            "latency_buffer", "minigame_difficulty", "minigame_trigger", "minigame_type",
            "motivation", "next_accuracy", "optimal_difficulty", "optimal_hint",
            "rhythm_complexity", "sub_routine", "time_pressure", "whats_missing_trigger"
        )
    }

    // ── State ──────────────────────────────────────────────────────────────────

    private var interpreter: Interpreter? = null
    var modelLoaded = false
        private set

    // name → TFLite output tensor index (loaded from JSON or discovered at runtime)
    private val outputNameToIndex = mutableMapOf<String, Int>()
    // TFLite index → shape
    private val outputShapes = mutableMapOf<Int, IntArray>()

    // Scaler parameters loaded from output_mapping.json
    // Applied to every feature vector before feeding to the model
    private var scalerMean  = FloatArray(NUM_FEATURES) { 0f }
    private var scalerScale = FloatArray(NUM_FEATURES) { 1f }
    private var scalerLoaded = false

    private val historyBuffer = ArrayDeque<FloatArray>(HISTORY_STEPS)

    // ── Init ───────────────────────────────────────────────────────────────────

    init {
        loadModel()
    }

    private fun loadModel() {
        Log.d(TAG, "════════════════════════════════════════")
        Log.d(TAG, "  GameMasterModel — Loading v9.2")
        Log.d(TAG, "════════════════════════════════════════")
        try {
            val buffer = loadModelFile()
            interpreter = Interpreter(buffer, Interpreter.Options().apply { numThreads = 2 })

            // Load JSON first — provides output mapping AND scaler params
            val jsonLoaded = loadOutputMappingJson()

            if (!jsonLoaded) {
                // JSON missing — fall back to runtime discovery
                Log.w(TAG, "⚠️  output_mapping.json not found — using runtime discovery (less reliable)")
                Log.w(TAG, "   Copy output_mapping.json to assets/ after retraining for correct mapping")
                discoverOutputLayout()
            }

            verifyOutputMapping()
            modelLoaded = true

            Log.d(TAG, "✅ Model loaded successfully")
            Log.d(TAG, "   Input tensors:  ${interpreter!!.inputTensorCount}")
            Log.d(TAG, "   Output tensors: ${interpreter!!.outputTensorCount}")
            logInputShapes()

        } catch (e: Exception) {
            modelLoaded = false
            Log.e(TAG, "❌ Model failed to load: ${e.message}")
            Log.e(TAG, "   Game will run with default values — no crash")
        }
    }

    // ── JSON Output Mapping + Scaler Load ──────────────────────────────────────

    /**
     * Loads output_mapping.json from assets.
     * Populates outputNameToIndex, outputShapes, scalerMean, scalerScale.
     *
     * The JSON is generated by export_model() in the Python script and contains:
     *   outputs.{name}.tflite_index  → which TFLite output tensor
     *   outputs.{name}.shape         → [1, size]
     *   scaler.mean                  → 17 floats, StandardScaler mean
     *   scaler.scale                 → 17 floats, StandardScaler scale
     *
     * Returns true if loaded successfully, false if file not found or parse error.
     */
    private fun loadOutputMappingJson(): Boolean {
        Log.d(TAG, "────────────────────────────────────────")
        Log.d(TAG, "  Loading output_mapping.json")
        Log.d(TAG, "────────────────────────────────────────")

        return try {
            val jsonString = context.assets.open(MAPPING_FILE)
                .bufferedReader()
                .use { it.readText() }

            val root    = JSONObject(jsonString)
            val version = root.optString("version", "unknown")
            Log.d(TAG, "   JSON version: $version")
            Log.d(TAG, "   Output order: ${root.optString("output_order", "unknown")}")

            // ── Output mapping ─────────────────────────────────────────────
            val outputs = root.getJSONObject("outputs")
            var mappedCount = 0

            for (name in outputs.keys()) {
                val entry      = outputs.getJSONObject(name)
                val tfliteIdx  = entry.getInt("tflite_index")
                val shapeArray = entry.getJSONArray("shape")
                val verified   = entry.optBoolean("verified", false)

                val shape = IntArray(shapeArray.length()) { shapeArray.getInt(it) }
                outputNameToIndex[name] = tfliteIdx
                outputShapes[tfliteIdx] = shape
                mappedCount++

                val verifyMark = if (verified) "✅" else "⚠️ "
                Log.d(TAG, "   $verifyMark '$name' → TFLite[$tfliteIdx] shape=${shape.contentToString()}")
            }

            Log.d(TAG, "   Mapped: $mappedCount / ${FALLBACK_EXPECTED_SIZES.size} outputs")

            // ── Scaler parameters ──────────────────────────────────────────
            if (root.has("scaler")) {
                val scalerJson = root.getJSONObject("scaler")
                val meanArray  = scalerJson.getJSONArray("mean")
                val scaleArray = scalerJson.getJSONArray("scale")
                val nFeatures  = scalerJson.optInt("n_features", NUM_FEATURES)

                if (meanArray.length() != NUM_FEATURES || scaleArray.length() != NUM_FEATURES) {
                    Log.e(TAG, "   ❌ Scaler size mismatch: JSON has ${meanArray.length()} features, expected $NUM_FEATURES")
                    Log.e(TAG, "      Retrain model and regenerate output_mapping.json")
                } else {
                    scalerMean  = FloatArray(NUM_FEATURES) { meanArray.getDouble(it).toFloat() }
                    scalerScale = FloatArray(NUM_FEATURES) { scaleArray.getDouble(it).toFloat() }
                    scalerLoaded = true

                    Log.d(TAG, "   ✅ Scaler loaded: $nFeatures features")
                    Log.d(TAG, "   Scaler mean  (first 5): ${scalerMean.take(5).map { "%.2f".format(it) }}")
                    Log.d(TAG, "   Scaler scale (first 5): ${scalerScale.take(5).map { "%.2f".format(it) }}")
                }
            } else {
                Log.w(TAG, "   ⚠️  No scaler in JSON — features will NOT be normalized (predictions may be wrong)")
                Log.w(TAG, "      Regenerate output_mapping.json with updated Python export script")
            }

            if (!scalerLoaded) {
                Log.e(TAG, "   ❌ Scaler NOT loaded — raw feature values will produce garbage predictions!")
                Log.e(TAG, "      Example: rt=3000 raw vs rt≈0.1 normalized. Model only understands normalized.")
            }

            Log.d(TAG, "✅ output_mapping.json loaded successfully")
            true

        } catch (e: java.io.FileNotFoundException) {
            Log.w(TAG, "   output_mapping.json not found in assets/")
            false
        } catch (e: Exception) {
            Log.e(TAG, "   Failed to parse output_mapping.json: ${e.message}")
            false
        }
    }

    fun seedHistory(tensor: Array<Array<FloatArray>>) {
        historyBuffer.clear()
        val rows = tensor.firstOrNull() ?: return
        for (row in rows) {
            if (row.any { it != 0f }) {   // skip zero-padding rows
                historyBuffer.addLast(row.copyOf())
            }
        }
        Log.d(TAG, "History seeded: ${historyBuffer.size} non-zero steps from previous session")
    }



    // ── Runtime Output Discovery (fallback if JSON missing) ────────────────────

    /**
     * Called only when output_mapping.json is not available.
     * Attempts name matching first, then alphabetical positional fallback.
     * Less reliable than JSON — copy output_mapping.json to assets to avoid this.
     */
    private fun discoverOutputLayout() {
        val interp = interpreter ?: return
        val count  = interp.outputTensorCount

        Log.d(TAG, "────────────────────────────────────────")
        Log.d(TAG, "  Runtime Output Discovery (fallback — $count tensors)")
        Log.d(TAG, "────────────────────────────────────────")

        val tfliteOutputs = mutableListOf<Triple<Int, String, IntArray>>()
        for (i in 0 until count) {
            val tensor = interp.getOutputTensor(i)
            val name   = tensor.name() ?: "null"
            val shape  = tensor.shape()
            tfliteOutputs.add(Triple(i, name, shape))
            Log.d(TAG, "   Raw TFLite[$i] name='$name' shape=${shape.contentToString()}")
        }

        // Try name matching
        var matched = 0
        for (pythonName in FALLBACK_ALPHA_ORDER) {
            val found = tfliteOutputs.firstOrNull { (_, n, _) -> n.contains(pythonName, ignoreCase = true) }
            if (found != null) {
                outputNameToIndex[pythonName] = found.first
                outputShapes[found.first]     = found.third
                matched++
                Log.d(TAG, "   ✅ Name-match: '$pythonName' → TFLite[${found.first}]")
            }
        }

        Log.d(TAG, "   Name-matched: $matched / ${FALLBACK_ALPHA_ORDER.size}")

        if (matched == 0) {
            Log.w(TAG, "   ⚠️  Zero name matches — using alphabetical positional fallback")
            Log.w(TAG, "   ⚠️  This is UNRELIABLE. Copy output_mapping.json to assets/ to fix.")
        }

        // Positional fallback
        for ((logicalIdx, pythonName) in FALLBACK_ALPHA_ORDER.withIndex()) {
            if (!outputNameToIndex.containsKey(pythonName) && logicalIdx < tfliteOutputs.size) {
                val (tfliteIdx, tfliteName, shape) = tfliteOutputs[logicalIdx]
                outputNameToIndex[pythonName] = tfliteIdx
                outputShapes[tfliteIdx]       = shape
                Log.d(TAG, "   📌 Positional[$logicalIdx]: '$tfliteName' → '$pythonName' shape=${shape.contentToString()}")
            }
        }

        // Store shapes for all indices
        for ((tfliteIdx, _, shape) in tfliteOutputs) {
            if (!outputShapes.containsKey(tfliteIdx)) outputShapes[tfliteIdx] = shape
        }
    }

    // ── Post-load shape verification ───────────────────────────────────────────

    /**
     * Verifies every resolved output has the expected last-dimension size.
     * A mismatch means the JSON is wrong (regenerate) or model architecture changed.
     */
    private fun verifyOutputMapping() {
        Log.d(TAG, "────────────────────────────────────────")
        Log.d(TAG, "  Output Shape Verification")
        Log.d(TAG, "────────────────────────────────────────")

        var passed = 0; var failed = 0

        for ((name, expectedSize) in FALLBACK_EXPECTED_SIZES) {
            val tfliteIdx  = outputNameToIndex[name]
            val shape      = if (tfliteIdx != null) outputShapes[tfliteIdx] else null
            val actualSize = shape?.last() ?: -1

            if (actualSize == expectedSize) {
                Log.d(TAG, "   ✅ $name: expected=$expectedSize actual=$actualSize [TFLite[$tfliteIdx]]")
                passed++
            } else {
                Log.e(TAG, "   ❌ MISMATCH $name: expected=$expectedSize actual=$actualSize [TFLite[$tfliteIdx]]")
                failed++
            }
        }

        Log.d(TAG, "────────────────────────────────────────")
        if (failed == 0) {
            Log.d(TAG, "  ✅ Shape verification PASSED: $passed / ${FALLBACK_EXPECTED_SIZES.size}")
            Log.d(TAG, "  ✅ All outputs mapped correctly")
        } else {
            Log.e(TAG, "  ❌ Shape verification FAILED: $failed mismatches, $passed correct")
            Log.e(TAG, "  ❌ Regenerate output_mapping.json by re-running Python export script")
        }
        Log.d(TAG, "────────────────────────────────────────")
    }

    private fun logInputShapes() {
        val interp = interpreter ?: return
        Log.d(TAG, "  Input shapes:")
        try {
            val cShape = interp.getInputTensor(0).shape()
            val hShape = interp.getInputTensor(1).shape()
            val fShape = interp.getInputTensor(2).shape()
            Log.d(TAG, "   [0] child_id : ${cShape.contentToString()}  expected=[1,1]  ${if (cShape.contentEquals(intArrayOf(1,1))) "✅" else "❌"}")
            Log.d(TAG, "   [1] history  : ${hShape.contentToString()}  expected=[1,5,17]  ${if (hShape.contentEquals(intArrayOf(1,5,17))) "✅" else "❌"}")
            Log.d(TAG, "   [2] current  : ${fShape.contentToString()}  expected=[1,17]  ${if (fShape.contentEquals(intArrayOf(1,17))) "✅" else "❌"}")
        } catch (e: Exception) {
            Log.w(TAG, "   Could not verify input shapes: ${e.message}")
        }
    }

    // ── Scaler ─────────────────────────────────────────────────────────────────

    /**
     * Applies StandardScaler normalization: (x - mean) / scale
     * Must be called on ALL feature vectors before feeding to the model.
     * Scaler params come from output_mapping.json (generated at training time).
     */
    private fun scaleFeatures(raw: FloatArray): FloatArray {
        if (!scalerLoaded) {
            // No scaler — return raw values with a warning (outputs will be wrong)
            return raw.copyOf(NUM_FEATURES)
        }
        return FloatArray(NUM_FEATURES) { i ->
            val x     = if (i < raw.size) raw[i] else 0f
            val mean  = scalerMean[i]
            val scale = scalerScale[i]
            if (scale == 0f) 0f else (x - mean) / scale
        }
    }

    // ── Public API ─────────────────────────────────────────────────────────────

    /** ALWAYS returns a valid Prediction — never throws, never returns null. */
    fun predict(childId: Int, currentFeatures: FloatArray): Prediction {
        updateHistory(currentFeatures)   // stores SCALED features

        if (!modelLoaded || interpreter == null) {
            Log.w(TAG, "⚠️ Model not loaded — returning defaults")
            return Prediction.defaults()
        }

        return try {
            runInference(childId, currentFeatures)
        } catch (e: Exception) {
            Log.e(TAG, "❌ Inference failed: ${e.message}")
            Log.e(TAG, "   Stack: ${e.stackTraceToString().lines().take(5).joinToString("\n   ")}")
            Log.e(TAG, "   Returning safe defaults — game continues")
            Prediction.defaults()
        }
    }

    /**
     * Convenience call with named parameters — pads missing features with safe defaults.
     * Never throws — returns Prediction.defaults() if model is unavailable.
     */
    fun predictSafe(
        childId:           Int,
        age:               Float = 8f,
        accuracy:          Float = 0.6f,
        engagement:        Float = 0.6f,
        frustration:       Float = 0.3f,
        jitter:            Float = 0.15f,
        rt:                Float = 3000f,
        consecutiveCorrect: Float = 0f,
        consecutiveWrong:  Float = 0f
    ): Prediction {
        val raw = FloatArray(NUM_FEATURES)
        raw[0]  = age
        raw[1]  = jitter
        raw[2]  = rt * 0.6f         // itl proxy
        raw[3]  = rt
        raw[4]  = 1400f             // hesitation default
        raw[5]  = accuracy
        raw[6]  = engagement
        raw[7]  = frustration
        // raw[8..11] = error types (default 0)
        raw[12] = consecutiveCorrect
        raw[13] = consecutiveWrong
        // raw[14..15] = response_decay, tap_variance (default 0)
        raw[16] = computeAlpha(accuracy, age.toInt(), rt)
        return predict(childId, raw)
    }

    // ── Inference ──────────────────────────────────────────────────────────────

    private fun runInference(childId: Int, currentFeatures: FloatArray): Prediction {
        val interp = interpreter!!

        Log.d(TAG, "── Running inference (childId=$childId) ──")

        // Scale raw features before feeding to model
        val scaledFeatures = scaleFeatures(currentFeatures)

        Log.d(TAG, "   Raw features (first 8): ${currentFeatures.take(8).map { "%.3f".format(it) }}")
        Log.d(TAG, "   Scaled features (first 8): ${scaledFeatures.take(8).map { "%.3f".format(it) }}")
        if (!scalerLoaded) {
            Log.e(TAG, "   ❌ WARNING: scaler not loaded — features are raw, predictions are garbage!")
        }
        _lastRawFeatures = currentFeatures.copyOf()

        // Inputs — history buffer already contains scaled values (see updateHistory)
        val childIdBuf: Array<FloatArray>        = Array(1) { floatArrayOf(childId.toFloat()) }
        val historyBuf: Array<Array<FloatArray>> = buildHistoryBuffer()
        val currentBuf: Array<FloatArray>        = Array(1) { scaledFeatures }
        val inputs: Array<Any>                   = arrayOf(childIdBuf, historyBuf, currentBuf)

        Log.d(TAG, "   childId=${childIdBuf[0][0]}  historySteps=${historyBuffer.size}  scalerLoaded=$scalerLoaded")

        // Outputs — allocated using actual shapes from model (not hardcoded)
        val outputCount = interp.outputTensorCount
        val outputMap   = HashMap<Int, Any>(outputCount)
        for (i in 0 until outputCount) {
            val shape = interp.getOutputTensor(i).shape()  // actual model, not JSON
            outputMap[i] = allocateOutputBuffer(shape)
        }

        interp.runForMultipleInputsOutputs(inputs, outputMap)
        Log.d(TAG, "   ✅ Inference call completed")

        logRawOutputs(outputMap)

        val prediction = parseOutputs(outputMap)
        logParsedPrediction(prediction)
        return prediction
    }

    fun lastFeatureVector(): FloatArray = _lastRawFeatures.copyOf()
    private fun logRawOutputs(outputMap: HashMap<Int, Any>) {
        Log.d(TAG, "  Raw output values (by logical name):")
        // Log in LABEL_COLS order for easier reading
        val logOrder = listOf(
            "next_accuracy", "future_engagement", "frustration_risk", "rhythm_complexity",
            "emotion_level", "optimal_difficulty", "interaction_mode",
            "minigame_trigger", "minigame_type", "minigame_difficulty",
            "whats_missing_trigger", "connect_dots_trigger", "hidden_step_index",
            "distractor", "friend_action", "sub_routine", "motivation",
            "optimal_hint", "latency_buffer", "time_pressure"
        )
        for (name in logOrder) {
            val tfliteIdx = outputNameToIndex[name] ?: continue
            val vec = extractVector(outputMap, tfliteIdx)
            val formatted = vec.joinToString(", ") { "%.3f".format(it) }
            Log.d(TAG, "   [TFLite $tfliteIdx] $name = [$formatted]")
        }
    }

    private fun logParsedPrediction(p: Prediction) {
        Log.d(TAG, "  ── Parsed Prediction ──────────────────")
        Log.d(TAG, "   nextAccuracy      = ${"%.3f".format(p.nextAccuracy)}")
        Log.d(TAG, "   futureEngagement  = ${"%.3f".format(p.futureEngagement)}")
        Log.d(TAG, "   frustrationRisk   = ${"%.3f".format(p.frustrationRisk)}")
        Log.d(TAG, "   latencyBuffer     = ${"%.3f".format(p.latencyBuffer)}  (${p.latencyBufferMs}ms)")
        Log.d(TAG, "   rhythmComplexity  = ${"%.3f".format(p.rhythmComplexity)}  (${p.rhythmSong})")
        Log.d(TAG, "   optimalDifficulty = ${p.optimalDifficulty}")
        Log.d(TAG, "   optimalHint       = ${p.optimalHint}")
        Log.d(TAG, "   friendAction      = ${p.friendAction}")
        Log.d(TAG, "   emotionLevel      = ${p.emotionLevel}")
        Log.d(TAG, "   subRoutine        = ${p.subRoutine}")
        Log.d(TAG, "   motivation        = ${p.motivation}")
        Log.d(TAG, "   distractor        = ${p.distractor}")
        Log.d(TAG, "   interactionMode   = ${p.interactionMode}")
        Log.d(TAG, "   timePressure      = ${p.timePressure}")
        Log.d(TAG, "  ── Mini-Game Triggers ─────────────────")
        Log.d(TAG, "   minigameTrigger     = ${p.minigameTrigger}  type=${p.minigameType}  diff=${p.minigameDifficulty}")
        Log.d(TAG, "   whatsMissingTrigger = ${p.whatsMissingTrigger}")
        Log.d(TAG, "   connectDotsTrigger  = ${p.connectDotsTrigger}  hiddenStep=${p.hiddenStepIndex}")
        Log.d(TAG, "   fromModel           = ${p.fromModel}")
        Log.d(TAG, "  ───────────────────────────────────────")
    }

    private fun allocateOutputBuffer(shape: IntArray): Any = when {
        shape.size == 1 -> FloatArray(shape[0])
        shape.size == 2 -> Array(shape[0]) { FloatArray(shape[1]) }
        shape.size == 3 -> Array(shape[0]) { Array(shape[1]) { FloatArray(shape[2]) } }
        else -> FloatArray(1)
    }

    private fun extractVector(outputMap: HashMap<Int, Any>, tfliteIdx: Int): FloatArray {
        val buf = outputMap[tfliteIdx] ?: return FloatArray(1)
        return when (buf) {
            is Array<*>   -> (buf[0] as? FloatArray) ?: FloatArray(1)
            is FloatArray -> buf
            else          -> FloatArray(1)
        }
    }

    private fun idx(name: String): Int =
        outputNameToIndex[name] ?: FALLBACK_ALPHA_ORDER.indexOf(name)

    private fun argmax(arr: FloatArray): Int =
        arr.indices.maxByOrNull { arr[it] } ?: 0

    private fun scalar(outputMap: HashMap<Int, Any>, name: String): Float =
        extractVector(outputMap, idx(name)).firstOrNull() ?: 0f

    private fun cls(outputMap: HashMap<Int, Any>, name: String): Int =
        argmax(extractVector(outputMap, idx(name)))

    private fun parseOutputs(outputMap: HashMap<Int, Any>): Prediction = Prediction(
        nextAccuracy        = scalar(outputMap, "next_accuracy").coerceIn(0f, 1f),
        futureEngagement    = scalar(outputMap, "future_engagement").coerceIn(0f, 1f),
        frustrationRisk     = scalar(outputMap, "frustration_risk").coerceIn(0f, 1f),
        latencyBuffer       = scalar(outputMap, "latency_buffer").coerceIn(0f, 1f),
        rhythmComplexity    = scalar(outputMap, "rhythm_complexity").coerceIn(0f, 1f),
        optimalDifficulty   = cls(outputMap, "optimal_difficulty"),
        optimalHint         = cls(outputMap, "optimal_hint"),
        friendAction        = cls(outputMap, "friend_action"),
        emotionLevel        = cls(outputMap, "emotion_level"),
        subRoutine          = cls(outputMap, "sub_routine"),
        motivation          = cls(outputMap, "motivation"),
        distractor          = cls(outputMap, "distractor"),
        minigameTrigger     = cls(outputMap, "minigame_trigger") == 1,
        minigameType        = cls(outputMap, "minigame_type"),
        minigameDifficulty  = cls(outputMap, "minigame_difficulty"),
        whatsMissingTrigger = cls(outputMap, "whats_missing_trigger") == 1,
        connectDotsTrigger  = cls(outputMap, "connect_dots_trigger") == 1,
        hiddenStepIndex     = cls(outputMap, "hidden_step_index"),
        interactionMode     = cls(outputMap, "interaction_mode"),
        timePressure        = cls(outputMap, "time_pressure"),
        fromModel           = true
    )

    // ── History ────────────────────────────────────────────────────────────────

    private fun buildHistoryBuffer(): Array<Array<FloatArray>> {
        val hist  = Array(HISTORY_STEPS) { FloatArray(NUM_FEATURES) }
        val start = maxOf(0, historyBuffer.size - HISTORY_STEPS)
        for (i in 0 until HISTORY_STEPS) {
            val srcIdx = start + i
            if (srcIdx < historyBuffer.size) hist[i] = historyBuffer[srcIdx].copyOf()
        }
        return arrayOf(hist)  // [1, 5, 17] — already scaled
    }

    /**
     * Stores SCALED features in history buffer.
     * History and current features must both be normalized before the model sees them.
     */
    private fun updateHistory(rawFeatures: FloatArray) {
        if (historyBuffer.size >= HISTORY_STEPS) historyBuffer.removeFirst()
        // Store scaled version — model was trained on normalized inputs
        historyBuffer.addLast(scaleFeatures(rawFeatures.copyOf(NUM_FEATURES)))
    }

    fun resetHistory() {
        historyBuffer.clear()
        Log.d(TAG, "History buffer reset")
    }

    // ── Utilities ──────────────────────────────────────────────────────────────

    private fun computeAlpha(accuracy: Float, age: Int, rt: Float): Float {
        val af    = 1.0f + ((age - 6) * 0.1f)
        val logRt = ln(max(1.0, rt / 1000.0) + 1.0).toFloat()
        return (accuracy * 10f * af / logRt).coerceIn(0f, 12f)
    }

    fun calculateAlpha(accuracy: Float, responseTime: Float, age: Int, errorCount: Int): Float {
        val af    = 1.0f + ((age - 6) * 0.1f)
        val rtSec = responseTime / 1000f
        return (accuracy * 10f * af /
                max(1f, ln((rtSec + errorCount + 1).toDouble()).toFloat()))
            .coerceIn(0f, 12f)
    }

    fun createInitialMetrics(age: Int): FloatArray {
        val f = FloatArray(NUM_FEATURES)
        f[0]  = age.toFloat()
        f[1]  = 0.10f   // jitter
        f[2]  = 1500f   // itl
        f[3]  = 3000f   // rt
        f[4]  = 1200f   // hesitation
        f[5]  = 0.5f    // accuracy
        f[6]  = 0.7f    // engagement
        f[7]  = 0.2f    // frustration
        f[15] = 0.08f   // tap_variance
        f[16] = 5.0f    // alpha
        return f
    }

    private fun loadModelFile(): MappedByteBuffer {
        for (path in listOf(MODEL_FILE, "ml/$MODEL_FILE")) {
            try {
                val fd = context.assets.openFd(path)
                Log.d(TAG, "✅ Found model at: $path  (${fd.declaredLength / 1024} KB)")
                return FileInputStream(fd.fileDescriptor).channel
                    .map(FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength)
            } catch (_: Exception) {}
        }
        throw Exception("Model file not found in assets ($MODEL_FILE)")
    }

    fun close() {
        interpreter?.close()
        interpreter = null
        modelLoaded = false
        Log.d(TAG, "Model closed")
    }
}


// ══ Prediction data class ═════════════════════════════════════════════════════

data class Prediction(
    val nextAccuracy:        Float,
    val futureEngagement:    Float,
    val frustrationRisk:     Float,
    val latencyBuffer:       Float,
    val rhythmComplexity:    Float,
    val optimalDifficulty:   Int,
    val optimalHint:         Int,
    val friendAction:        Int,
    val emotionLevel:        Int,
    val subRoutine:          Int,
    val motivation:          Int,
    val distractor:          Int,
    val minigameTrigger:     Boolean,
    val minigameType:        Int,
    val minigameDifficulty:  Int,
    val whatsMissingTrigger: Boolean,
    val connectDotsTrigger:  Boolean,
    val hiddenStepIndex:     Int,
    val interactionMode:     Int,
    val timePressure:        Int,
    val fromModel:           Boolean = false
) {
    companion object {
        fun defaults() = Prediction(
            nextAccuracy        = 0.6f,
            futureEngagement    = 0.6f,
            frustrationRisk     = 0.3f,
            latencyBuffer       = 0.5f,
            rhythmComplexity    = 0.3f,
            optimalDifficulty   = 1,
            optimalHint         = 0,
            friendAction        = 0,
            emotionLevel        = 0,
            subRoutine          = 1,
            motivation          = 1,
            distractor          = 0,
            minigameTrigger     = false,
            minigameType        = 0,
            minigameDifficulty  = 0,
            whatsMissingTrigger = false,
            connectDotsTrigger  = false,
            hiddenStepIndex     = 2,
            interactionMode     = 0,
            timePressure        = 0,
            fromModel           = false
        )
    }

    val latencyBufferMs: Long
        get() = (latencyBuffer * 10000f).toLong().coerceIn(2000, 10000)

    val rhythmSong: String
        get() = when {
            rhythmComplexity < 0.33f -> "Row Row Row Your Boat"
            rhythmComplexity < 0.66f -> "Jack and Jill"
            else                     -> "Twinkle Twinkle"
        }
}